### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by TheAio**
Added a readme file based of the text in the website; https://bot.konkenbonken.se/

### CODE REVIEW

**Review by KonkenBonken — COMMENTED** [review]
Why did you remove the headers?

**Comment by KonkenBonken** [comment]
I see, I think I found your problem
To make a header in markdown, the syntax is `# Header` (with a space), not `#Header` as in [your commit](https://github.com/KonkenBonken/KonkenBoten/commit/17689529b4bace1b3f5f4d3233a8d334b318b3f0)
I'll fix it now, and then merge.
Thanks a lot for the pull request :)

**Review by KonkenBonken — APPROVED** [review]
Became quite a lot of edits 😅
Are you, @TheAio, okay with the current version? Feel free to suggest any change,
I'll merge otherwise 🙂

**Comment by TheAio** [comment]
I think it looks great.

**Pull request merged**
